DELETE https://phonebook-fullstack-course.herokuapp.com/api/persons/577546

###
POST https://phonebook-fullstack-course.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Clay Slayton",
    "number": "032-3456-987"
}